---
printWidth: 100
tabWidth: 4
useTabs: false
trailingComma: all
semi: true
singleQuote: false
overrides:
  - files: "*.{md,yml,yaml}"
    options:
      tabWidth: 2

plugins:
  - prettier-plugin-svelte
  - prettier-plugin-organize-imports
  - prettier-plugin-tailwindcss

organizeImportsSkipDestructiveCodeActions: true

tailwindConfig: packages/baha-anime-skip-ext/tailwind.config.cjs
