name: Build Script

on:
  push:
    branches:
      - main
    paths:
      - packages/baha-anime-skip/**
  workflow_dispatch:

jobs:
  build_script:
    name: Build Script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.4
        with:
          run_install: true

      - name: Build
        run: pnpm -r run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN  }}
          publish_dir: "./packages/baha-anime-skip/dist"
          publish_branch: "dist"
